### ISSUE TITLE
Успешный платеж не перехватывается

### ISSUE THREAD

**Issue by bumsun** [yandex-money/yandex-money-sdk-android#10]
Не срабатывает метод onActivityResult при успешной оплате

**Comment by yasevich** [comment]
Пожалуйста, уточните пользовательский сценарий при котором воспроизводится эта ошибка.

**Comment by andrew-k-21-12** [comment]
У меня тоже. Возможно, неверно что-то конфигурировал. 
Производил платёж картой в магазин (код представлен здесь - https://github.com/yandex-money/yandex-money-sdk-android/issues/16). На экране в WebView после успешного платежа появляется надпись "Спасибо! С вашей карты списано N руб.". Как понимаю, именно в этот момент PaymentActivity должна закрыться, прислав результат, но этого не происходит.

**Comment by andrew-k-21-12** [comment]
Предположу, что метод applyResult(); должен вызываться до родительского super.onBackPressed();, иначе результат не успевает примениться.

**Comment by glnix** [comment]
Кто нибудь нашел решение?

**Comment by andrew-k-21-12** [comment]
мне помогло в коде PaymentActivity библиотеки в методе onBackPressed переместить вызов метода applyResult выше super.onBackPressed()

**Comment by yasevich** [comment]
Опубликовал сегодня версию 3.0.5. Она включает в себя изменения, связанное с этим багом.

Подключить новую версию можно так:

```
compile 'com.yandex.money.api:yandex-money-sdk-android:3.0.5'
```
