### ISSUE TITLE
Incorrect package name

### ISSUE THREAD

**Issue by AlexGontarenko** [yandex-money/yandex-money-sdk-android#12]
PaymentActivity у Вас в пакете ru.yandex.money...
а добавление в проект library идет через

dependencies {
    compile 'com.yandex.money.api:yandex-money-sdk-android:3.0.4'
}

Итог - в упор не видит он Ваш PaymentActivity

**Comment by yasevich** [comment]
Alex, уверяю вас, проблема не может быть в этом.

Возможно вам нужно синхронизировать проект после добавления его в dependencies. Так же убедитесь, что ваши import'ы ведут по правильному пути.

**Comment by AlexGontarenko** [comment]
AndroidStudio глючит, конечно, но не уверен, что настолько... PaymentParams нормально видел, при подключенном только yandex-money-sdk-android, которое, вообще-то, в другой либе даже... а вот PaymentActivity вручную подсовывал - результата нуль... синхронизировал проект не один раз,     пересобирал, чистил - не подцепил он зависимость...

Еще было бы полезным описать правила для стилей, чтобы их можно было у себя в приложении переопределить (цвет ActionBar, иконка в нем, текст...)

**Comment by raymank26** [comment]
Получилось ли у вас запустить проект? Если нет, то попробуйте импортировать в Android Studio (последней версии) наш sample.

**Comment by AlexGontarenko** [comment]
Да так и сделал несколько дней назад, но все таки хотелось бы иметь импорт либы =)

Добавьте, пожалуйста, в описание или в ВИКИ описание стилевых настроек (чтобы в будущем людям не ковыряться в проекте)

<style name="ym_theme" parent="MyAppTheme">
        <item name="android:icon">@drawable/ic_logo</item>
        <item name="android:actionBarStyle">@style/MyAppYandex.ActionBar</item>
</style>

<style name="MyAppYandex.ActionBar" parent="MyApp.ActionBar">
        <item name="android:indeterminateProgressStyle">@style/IndeterminateProgress</item>
</style>

<style name="IndeterminateProgress" parent="@android:style/Widget.ProgressBar">
        <item name="android:indeterminateDrawable">@drawable/custom_progress</item>
</style>
