### ISSUE TITLE
Проведение платежей для сохраненных карт

### ISSUE THREAD

**Issue by AlexGontarenko** [yandex-money/yandex-money-sdk-android#13]
Если после успешного платежа сохранить карту и повторно проводить платеж с этой карты, то можно вводить любой CVC код и выйдет уведомление о успешном платеже

**Comment by raymank26** [comment]
Добрый день!

Проверять CVC-код задача банка-эмитента карты клиента. При этом политика банка может быть различной. Например, банк может не проверять CVС-код до определенной суммы.

**Comment by AlexGontarenko** [comment]
Спасибо за оперативный ответ!
Не планируется ли в дальнейшем модификация (не запрашивать CVC, если банк его не требует), поскольку сейчас смотрится как уязвимость?

**Comment by raymank26** [comment]
Мы со своей стороны не можем знать заранее, будет ли банк проверять CVC-код или нет, поэтому поле ввода кода является обязательным.

**Comment by AlexGontarenko** [comment]
Спасибо!
