### ISSUE TITLE
Не работает оплата банковской картой ВТБ24

### ISSUE THREAD

**Issue by VyacheslavShmakin** [yandex-money/yandex-money-sdk-android#15]
Открывается форма с запросом заполнения данных о банковской карте в WebView с uri следующего вида:
https://m.sp-money.yandex.ru/pay/api/carddetails?cps_context_id=[context id]

После заполнения формы каждый раз получаю ответ от сервера следующего вида:
yandex-money-sdk-android://fail?orderN=[order number]&cps_email=&cps_card=[card number]&merchant_order_id=[merchant order id]&cps_context_id=[context id]&skr_env=api&skr_hold=false&reason=technical&status=error&sum=[sum]

И такое ТОЛЬКО при попытке оплаты картой ВТБ24 и ТОЛЬКО на андроид-версии SDK. В иных случаях, после заполнения формы с данными о карте открывается следующая ссылка, адресующая на страницу с 3D-SECURE. Далее, платёж завершается успешно.

P.S. Очень неплохо было бы увидеть РАБОЧИЙ пример кода с оплатой банковской картой, либо Яндекс.Деньгами.

**Comment by raymank26** [comment]
Добрый день!

Напишите нам https://money.yandex.ru/feedback/ с указанием параметров платежа. Маловероятно, что ошибка связана с android sdk.
