### ISSUE TITLE
Как правильно осуществить платёж для магазина?

### ISSUE THREAD

**Issue by andrew-k-21-12** [yandex-money/yandex-money-sdk-android#16]
Доброго времени суток! Уже теряюсь в догадках, использую следующий код:

Map<String, String> params = new HashMap<>();
                    params.put("shopId", "" + SHOP_ID);
                    params.put("scid", "" + SC_ID);
                    params.put("sum", "" + mSum);
                    params.put("customerNumber", "" + mUserId);
                    params.put("paymentType", "AC");
                    params.put("saleOrderId", "" + mOrderId);
startPaymentActivityForResult(new ShopParams("" + SC_ID, params));

Собственно метод вызова активити для платежа:

private void startPaymentActivityForResult(PaymentParams paymentParams) {
        Intent intent = PaymentActivity.getBuilder(this)
                .setPaymentParams(paymentParams)
                .setClientId(CLIENT_ID)
                .setHost(HOST)
                .build();
        startActivityForResult(intent, REQUEST_CODE);
    }

Если использовать https:/demomoney.yandex.ru для HOST, то получаю:
error=TECHNICAL_ERROR,status=refused
в случае https://money.yandex.ru:
error=ILLEGAL_PARAM_INSTANCE_ID,status=refused

Что делаю не так? В логах вроде параметр instance_id имеется.

**Comment by raymank26** [comment]
Добрый день!

Параметры для платежа должны содержать тот набор параметров, который вы получили от вашего менеджера. Список параметров зависит от вашего способа подключения, подробнее про их значения можно прочитать по ссылке:

https://tech.yandex.ru/money/doc/payment-solution/payment-form/payment-form-docpage/

При платеже через API (используя android sdk), вы должны указать scid как pattern_id, остальные параметры оставить без изменений(см. https://tech.yandex.ru/money/doc/dg/reference/request-external-payment-docpage/). Правила их формирования те же. Если вы подключаетесь по HTTP-протоколу, то вам потребуется реализовать и серверную часть для успешного проведения платежа.

Чтобы узнать, являются ли параметры платежа правильными - лучше всего воспользоваться каким-либо REST-клиентом, получив instance_id(один раз для каждого хоста) и вызвать метод ```request-external-payment```. Если в ответе вместо ошибки вы получите ```request_id```, то значит набор параметров верный. Можно переносить код в android-приложение.

> Если использовать https:/demomoney.yandex.ru для HOST, то получаю:
> error=TECHNICAL_ERROR,status=refused
> в случае https://money.yandex.ru:
> error=ILLEGAL_PARAM_INSTANCE_ID,status=refused

При переключении хостов стирать данные приложения обязательно, т.к. instance_id одного хоста не подходит к другому.

**Comment by andrew-k-21-12** [comment]
Спасибо за оперативный и развернутый ответ.

Помогла очистка памяти приложения при смене хоста.

**Comment by AlexKravt** [comment]
Здравствуйте! 
Стал использовать API yandex-money-sdk-android и не нашёл пример авторизации приложения для оплаты с яндекс кошелька.
Где можно посмотреть  или  будет ли такая реализация в sample для демонстрации примера? 
В предыдущей версии API [Java-Yandex.Money-API-SDK](https://github.com/melnikovdv/Java-Yandex.Money-API-SDK/tree/master/yamodroid) такая возможность была реализована. 
Могу я использовать данную реализацию или этот пример из данной API работать не будет?

**Comment by yasevich** [comment]
Добрый день.

Текущая версия SDK для Android позволяет совершать платежи только в неавторизованном состоянии с произвольной банковской карты. Но в [SDK для Java](https://github.com/yandex-money/yandex-money-sdk-java) есть все необходимые для этого методы. Пример того, как выполнить авторизацию описан [здесь](https://github.com/yandex-money/yandex-money-sdk-java/blob/master/README.md) в секции Performing Request.

Старая версия SDK больше не поддерживается и гарантировать её правильную работу я не могу.

**Comment by AlexKravt** [comment]
Спасибо за оперативный ответ!

**Comment by AlexKravt** [comment]
Здравствуйте!
Выше Вы дали подсказку, на реализацию, но мне не совсем понятно как это использовать в webview? 
Так как судя по документации нужно реализовать перенаправление пользователя в браузер нпример (Chrome) и одновременно отправить запрос на подтверждение авторизации.
После чего нужно, каким то образом перехватить redirect.
В данной реализации, что Вы указали, используется, я так понял отправка данных методом POST через клиент **client.createAuthorizationData(params)** на URL  авторизации и без открытия страницы пользователю.

Может я, что то не понимаю?
Спасибо!

**Comment by HITALIKvITALYI** [comment]
передавая  instance_id  используя SDK com.yandex.money.api:yandex-money-sdk-android:4.1.0 приведет к ошибке так как  request-external-payment будет содержать instance_id вновь полученный(и так как он геренируетсся при каждом обращении новый )  будет отличатся от  process-external-payment (так как он был получен при первом запуске). и тут момент SharedPreferences реализованный в API не переписывает instance_id, а держит постоянно первое полученное значение, соответственно так как мы ранее использовали CLIENT_ID для демо платежей то в SharedPreferences будет содержать не верный instance_id...

**Comment by heapify54** [comment]
Добрый день. Почему при попытке получить instance-id, вызывая метод https://money.yandex.ru/api/instance-id c client_id, только что полученный в яндекс деньгах, я всегда получаю ошибку:
 {
    "error": "illegal_param_client_id",
    "status": "refused"
}

Подскажите пожалуйста, почему так происходит?

**Comment by AlexKravt** [comment]
Ответ можете получить прочитав коммент от HITALIKvITALYI выше, возможно в этом ваша проблема. Просто почистите SharedPreferences.

**Comment by HITALIKvITALYI** [comment]
Добрый!, вопрос еще актуален?

11 ноября 2017 г., 23:13 пользователь heapify54 <notifications@github.com>
написал:

**Comment by HITALIKvITALYI** [comment]
нет времени все писать, свяжитесь по скайпу hitalik1986@gmail.com, все разъясню, но в данном случае просьба  решение выложить сюда!

**Comment by HITALIKvITALYI** [comment]
Я сам много времени убил на это, и  Яндекс  к сожалению не ведет активную работу над  Api для Android.
    Рекомендую прежде чем хвататься за Android для начало проверить правильные ли параметры  Вы используете, и корректно ли работают скрипты **check.php и aviso.php**, для этого лучше всего использовать _html_.
 
 Вот верный код _html_ c необходимыми параметрами для БОЕВЫХ ПЛАТЕЖЕЙ ссылка для демо будет https://demomoney.yandex.ru/eshop.xml. Особое внимание к **ym_merchant_receipt** (параметр для кассы).


<form action="https://money.yandex.ru/eshop.xml" method="post"> 
    <input name="shopId" value="******" type="hidden"/>
    <input name="scid" value="******" type="hidden"/>
    <input name="customerNumber" value="7777" type="hidden"/>
    <input name="paymentType" value="AC" type="hidden"/>
    <input name="orderNumber" value="7777" type="hidden"/>
    <input name="cps_phone" value="+79************" type="hidden"/>
    <input name="cps_email" value="hitalik1986@gmail.com" type="hidden"/>
    <input name="ym_merchant_receipt"
    value='{"customerContact": "hitalik1986@gmail.com", "taxSystem": 1,
          "items":[
    {"quantity": 1,     "price": {"amount": 70.00},    "tax": 1,"text": "Привет))"},
            {"quantity": 1,     "price": {"amount": 100.00},    "tax": 1,"text": "доставка"}
                  ]}'
type="hidden"/>
<input name="sum" value="170.00" type="hidden"/>
 <input type="submit" value="OK"/>
</form
```

 Если у Вас проходит платеж, значит Вы имеете правильный набор параметров, и с скриптами **check.php и aviso.php** все в порядке. 

Можно переходить к коду для андроид.
        Не используйте демо пример от яндекса! “Столько грязи”  создайте новый проект.
       Не пихайте сразу код в основной проект.
```
Подключаем   compile 'com.yandex.money.api:yandex-money-sdk-android:4.1.0'
 Для тестов Вам поможет Вот этот код
 
package com.;
import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import com.yandex.money.api.methods.payment.params.PaymentParams;
import com.yandex.money.api.methods.payment.params.ShopParams;
import java.util.HashMap;
import java.util.Map;
import ru.yandex.money.android.PaymentActivity;

public class ActivityStoreMarket extends AppCompatActivity
{
 private static final String LOG_TAG = "ActivityStoreMarket";
 private static final int REQUEST_CODE = 1;
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_store_market);
                    Map<String, String> params = new HashMap<>();
                    String scid = "******";
                    params.put("shopId", "******");//Идентификатор магазина, 
                    params.put("scid", scid);//Идентификатор витрины магазина
                    params.put("customerNumber", "test43256");
                    params.put("paymentType", "AC");
                    params.put("orderNumber", "test4324");
                    params.put("cps_phone", "+7************");
                    params.put("cps_email", "hitalik1986@gmail.com");
                    params.put("ym_merchant_receipt", "{\"customerContact\": \"hitalik1986@gmail.com\",\n" +
                            " \"taxSystem\": 1,\n" +
                            "  \"items\":[\n" +
                            "\t\t    {\"quantity\": 1,     \"price\": {\"amount\": 100.00},    \"tax\": 1,\"text\": 
                            \"услуга\"},\n" +
                            "            {\"quantity\": 1,     \"price\": {\"amount\": 50.00},    \"tax\": 1,\"text\": 
                           \"доставка\"}\n" +
                            "                  ]}");
                    params.put("sum", "150.00");//Сумма заказа
                    startPaymentActivityForResult(new ShopParams(scid,params));
    }

    private void startPaymentActivityForResult(PaymentParams paymentParams)
    {
        final String CLIENT_ID = "***********************************";
        final String HOST = "https://money.yandex.ru/eshop.xml";// ДЛЯ РЕАЛЬНЫХ ПЛАТЕЖЕЙ   
        Intent intent = PaymentActivity.getBuilder(this)
                .setPaymentParams(paymentParams)
                .setClientId(CLIENT_ID)
                .setHost(HOST)
                .build();
        startActivityForResult(intent, REQUEST_CODE);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent Intent_data)
    {
        if (requestCode == REQUEST_CODE && resultCode == RESULT_OK)
        {
            Log.d(LOG_TAG,resultCode+"успешно");
        }
        else {
            Log.d(LOG_TAG, resultCode + "");
        }
    }
}
```
 
     Итак мы имеем минимум кода, он прост и прозрачен, что дает нам ясность происходящего...  типо ).
Вас может смутить то что  имена параметров отличаются от тех которые мы указываем в _HTML_, но я не ошибся! .
    Вы обратили внимание что я негде не получаю и не  передаю параметр instance_id?.
 Почему ? давайте разбираться!.
      Документация Яндекса нам говорит, что мы должны единожды получить instance_id, и далее до последнего передавать его во всех запросах, но они забыли нам сказать, что это в том случае если мы пишем api сами, более того! они забыли это сказать даже своей тех. Поддержке )), это не шутка.
  
    Давайте рассмотрим на практике что происходит.
Передадим instance_id как параметр добавим его в нашу карту   params.put(“instance_id”,   ‘**tPilDkEU%2FhPmpIQmUZvOVP9Dww91D4RqdNmeJ3vuoC3xXdYqfvBwRSDbwxWpIWu6**’);
 
**Запускаем!.
Смотрим логи.**
 
```
POST //api/request-external-payment HTTP/1.1[\r][\n]
...
[\r][\n]
paymentType=AC&shopId=147217&orderNumber=137&customerNumber=test&sum=350&pattern_id=********&instance_id=tPilDkEU%2FhPmpIQmUZvOVP9Dww91D4RqdNmeJ3vuoC3xXdYqfvBwRSDbwxWpIWu6
...
 
POST //api/process-external-payment HTTP/1.1[\r][\n]
[\r][\n]
request_id=333331353733383534305f39353366343033613463396537386431333065613930663862303231363466623933666438633266
&ext_auth_success_uri=yandex-money-sdk-android%3A%2F%2Fsuccess
&ext_auth_fail_uri=yandex-money-sdk-android%3A%2F%2Ffail&request_token=false
&instance_id=BBn3Ex%2B8s8BsRWQliQQLZiWo24Mc%2B8NPQE68lvKbRmLzbcZ4mHIa1f2kTe6%2BvuzK
...
HTTP/1.1 200 OK[\r][\n]
Date: Wed, 27 Sep 2017 12:16:42 GMT[\r][\n]
...
I/ponseLoggingInputStream: {"status":"refused","error":"illegal_param_instance_id"}
```
 
И у нас ошибка illegal_param_instance_id.
Ок смотрим  request-external-payment принял наш instance_id.
Но у  process-external-payment совершенно другой instance_id.
  
 **Чего))
request-external-payment instance_id=
tPilDkEU%2FhPmpIQmUZvOVP9Dww91D4RqdNmeJ3vuoC3xXdYqfvBwRSDbwxWpIWu6         
process-external-payment instance_id=BBn3Ex%2B8s8BsRWQliQQLZiWo24Mc%2B8NPQE68lvKbRmLzbcZ4mHIa1f2kTe6%2BvuzK**

Да дело в в том что Api начихать что мы там передаем, почему так?, да все просто в Api уже реализован метод получения  instance_id, чтоб продолжить дальше надо понимать если мы будем посылать запрос для получения instance_id каждый раз мы будем получать новое значение
 
Поэкспериментируйте: вот пример запроса на получения instance_id. (данный пример еще позволит понять валидный ли у вас client_id)
 
```
Request URL:https://money.yandex.ru/api/instance-id
Request Method:POST
Status Code:200 OK
client_id:***************************************************************************
Response:
{"instance_id":"2bwnrpisjgSEBQrotn+Vjx1UESSLOkj2MA88+D9X3CyXrWOWrLBrQH4oW0U6ANGy","status":"success"}
```

И тут становится понятно почему у нас разный instance_id
  с начало мы отправили запрос на получение, 
  потом api дойдя до метода process-external-payment делает запрос на получение 
  в итоге и нас разные instance_id в запросах и мы получаем ошибку.
   Но на этом еще не все.
 Давайте посмотрим как Api его получает. 
Откройте PaymentActivity (Яндекс Api)
В этом классе есть метод initPaymentProcess собственно он и является виновником проблемы.
 
```
private boolean initPaymentProcess() 
{
    final Intent intent = getIntent();
    final String clientId = intent.getStringExtra(EXTRA_CLIENT_ID);
    final String host = intent.getStringExtra(EXTRA_HOST);
    final ApiClient client = new DefaultApiClient.Builder()
           .setClientId(clientId)
            .setHostsProvider(new DefaultApiV1HostsProvider(true) {
              
    @Override
                public String getMoney() {
                    return host;
                }
            })
            .setDebugMode(!PRODUCTION_HOST.equals(host))
            .create();
    process = new ExternalPaymentProcess(client, this);
 
   final Prefs prefs = new Prefs(this);
   String instanceId = prefs.restoreInstanceId();

 if (TextUtils.isEmpty(instanceId)) {
        perform(() -> client.execute(new InstanceId.Request(clientId)), response -> {
            if (response.isSuccessful()) {
                prefs.storeInstanceId(response.instanceId);
                process.setInstanceId(response.instanceId);
                proceed();
            } else {
                showError(response.error, response.status.toString());
            }
        });
        return false;
    }
    process.setInstanceId(instanceId);
    return true;
}
```
 
То есть  **if (TextUtils.isEmpty(instanceId))**  он тупо в prefs  проверяет запись об InstanceId, представите сколько гемора доставил этот кусок кода, если он бы как доп условие учитывал смену **clientId**, я думаю что на начальном проектировании не было понятия как DEMO платежи, иначе как можно было допустить такую глупую ошибку. Данным комментарием я хотел помочь последовательно подойти к решению этой проблемы, и объяснить причину по которой приходится очищать  SharedPreferences, это недоразумение в методе  initPaymentProcess **при смене  clientId приведет к невозможности оплачивать с вашего приложения задумайтесь над этим это нельзя так просто оставить!.**

**Comment by HITALIKvITALYI** [comment]
heapify54 в Вашем случае вы используете client_id для реальных платежей, а Вам надо для демо, в инете куча инфы для его получения, но как я описал выше нет необходимости в получении instanceId

**Comment by heapify54** [comment]
Спасибо! Вы все правильно сказали, сделали demo приложение и все получилось.
Однако теперь вот такой момент:

Зарегистрировали client_id в demomoney.yandex.ru.
Получили демо scid и shopid

Далее выполняем такой код и получаем ошибку: ru.yandex.money.android.fragments.ErrorFragment: error=PAYMENT_REFUSED,status=REFUSED

String scId = "*****";

Map<String, String> shopParams = new HashMap<>();

shopParams.put("shopId", "******");
shopParams.put("scid", scId);
shopParams.put("sum", "1");

PaymentParams params = new ShopParams(scId, shopParams);

Intent intent = PaymentActivity
.getBuilder(getContext())
.setPaymentParams(params)
.setClientId(DEMO_CLIENT_ID)
.setHost(DEMO_HOST)
.build();

startActivityForResult(intent, REQUEST_CODE);

При этом была использована демо карта 4444 4444 4444 4448

Т.е. вводим карту, начинаем оплату, но она не проходит, выдается ошибка выше
Подскажите, в чем может быть проблема?

**Comment by HITALIKvITALYI** [comment]
У вас метод подключения Http?,  я к тому что вы указывали пути к файлам на сервере  check.php и aviso.php?

**Comment by HITALIKvITALYI** [comment]
Поле подробно по  check.php и aviso.php, их реализацию, вылажу в воскресенье.

**Comment by HITALIKvITALYI** [comment]
Сложно ответить на ваш вопрос! так как судя по примеру кода приведенного Вами, Вы не воспользовались моим рекомендациям по реализации, и Вы не предоставили полные логи!, снимите фильтр легирования  в студии с вашего пакета, чтоб посмотреть более детально вашу проблему.

**Comment by HITALIKvITALYI** [comment]
Извиняюсь за каламбур)) в свободное время приведу свои коменты в порядок, на данный момент у  Вас не полный shopParams. Изучите мои комент про instance_id, там есть ответы на Все ваши проблемы!

**Comment by heapify54** [comment]
Всем привет, сейчас столкнулись с такой проблемой, при работе с демо все получилось, платежи проходили. Мы запросили боевые данные, установили их, но теперь ничего не сработало. Ошибка явно не выдается, но в логах было: https://money.yandex.ru/payments/fail?reason=invalid-scid

Естественно и хост боевой и client_id

В чем может быть беда?
Также настроен и ym_merchant_receipt
