### ISSUE TITLE
TECHNICAL_ERROR при вызове PaymentActivity

### ISSUE THREAD

**Issue by Bolid** [yandex-money/yandex-money-sdk-android#17]
Доброго дня!
Использую такой простой код для вызова оплаты в магазине:
HashMap<String, String> params = new HashMap<>();
        params.put("shopId", SHOP_ID);
        params.put("scid", SCID);
        params.put("sum", "1.00");
        params.put("customerNumber", "123");
        PaymentParams param = new ShopParams(SCID, params);
        Intent intent = PaymentActivity.getBuilder(getBaseContext())
                .setPaymentParams(param)
                .setClientId(CLIENT_ID)
                .setHost(HOST)
                .build();
        startActivityForResult(intent, REQUEST_CODE);

хост такой https:/demomoney.yandex.ru/
Возникает ошибка "Ой! Платеж не прошел..." и в логе {"status":"refused","error":"technical_error"}
В чем может быть причина? Почитал другие issues по теме, но ничего не помогает.

**Comment by yasevich** [comment]
Добрый день, код ```technical_error``` означает, что портал не смог обработать ваш запрос из-за внутренней ошибки сервера.

Пожалуйста, напишите нам [сюда](https://money.yandex.ru/feedback/), если эта проблема повторяется.
