### ISSUE TITLE
Не проходит платеж, ошибка error=PAYMENT_REFUSED, status=refused

### ISSUE THREAD

**Issue by koderbober** [yandex-money/yandex-money-sdk-android#19]
Не могу понять, в чем проблема, активити оплаты успешно запускается, после заполнения данных о банковской карте банк пытается провести платеж, яндекс.касса в операциях этот платеж даже отображает, но он остается висеть в обработке, а в приложении в логах указывается только error=PAYMENT_REFUSED, status=refused и больше никакой информации о том, почему платеж в итоге не проходит. Способ подключения магазина к яндекс.кассе, если я не ошибаюсь, через HTTP-протокол. Код запуска активити выглядит так:

                    Map<String, String> params = new HashMap<>();

                    //идентификатор магазина
                    params.put("shopId", "" + SHOP_ID);

                    //способ оплаты, AC - оплата с произвольной банковской карты
                    params.put("paymentType", "AC");

                    //номер витрины магазина
                    params.put("scid", "" + SC_ID);

                    //сумма заказа
                    params.put("sum", "" + "1");

                    //id плательщика в системе магазина
                    params.put("customerNumber", "" + ID);

                    PaymentParams paymentParams = new ShopParams("" + SC_ID, params);
                    Intent intent = PaymentActivity.getBuilder(getApplicationContext())
                            .setPaymentParams(paymentParams)
                            .setClientId(CLIENT_ID)
                            .setHost(HOST)
                            .build();
                    startActivityForResult(intent, REQUEST_CODE);

В чем все-таки может быть проблема, необходимо указывать еще какие-то параметры?

**Comment by yasevich** [comment]
Пожалуйста, напишите [сюда](https://money.yandex.ru/feedback/), попробуем разобраться в чём проблема.

**Comment by mifkamaz** [comment]
А в чем проблема-то была?

**Comment by heapify54** [comment]
Добрый день. Аналогичная проблема:

Зарегистрировали client_id в demomoney.yandex.ru.
Получили демо scid и shopid

Далее выполняем такой код и получаем ошибку: ru.yandex.money.android.fragments.ErrorFragment: error=PAYMENT_REFUSED,status=REFUSED

String scId = "*****";

Map<String, String> shopParams = new HashMap<>();

shopParams.put("shopId", "******");
shopParams.put("scid", scId);
shopParams.put("sum", "1");

PaymentParams params = new ShopParams(scId, shopParams);

Intent intent = PaymentActivity
   .getBuilder(getContext())
   .setPaymentParams(params)
   .setClientId(DEMO_CLIENT_ID)
   .setHost(DEMO_HOST)
   .build();

startActivityForResult(intent, REQUEST_CODE);

При этом была использована демо карта 4444 4444 4444 4448

Подскажите, в чем может быть проблема?

**Comment by koderbober** [comment]
@heapify54 у меня проблема была в итоге с нашим бэком, а не яндексовым, ибо он тоже на своей стороне проверяет введенные данные, а если правильно помню (давно это было), там какие-то кастомные данные для ввода можно задавать и их может не хватать, могут быть неправильно переданы и т.д. Ну и собственно неяндексовый бэк может не подтвердить данные, а тогда яндексовый вернет по сути ноунейм ошибку и не проведет платеж.
