### ISSUE TITLE
Конфликт из-за android:allowBackup

### ISSUE THREAD

**Issue by Aleat0r** [yandex-money/yandex-money-sdk-android#21]
Здравствуйте. Зачем в sdk в манифесте есть android:allowBackup="false" ? Это приводит к ошибке, если в приложении используется "true". Вариант исправления этой проблемы с помощью 'tools:replace="android:allowBackup"' не работает.

**Comment by EnterPrayz** [comment]
Та же тема, как решить?

**Comment by yasevich** [comment]
Исправлено #23.
