### ISSUE TITLE
AUTHORIZATION_REJECT

### ISSUE THREAD

**Issue by mifkamaz** [yandex-money/yandex-money-sdk-android#25]
Создаю оплату при помощи этого кода.

        Map<String, String> params = new HashMap<>();
        params.put("shopId", Integer.toString(SHOP_ID));
        params.put("scid", Integer.toString(SC_ID));
        params.put("sum", Integer.toString(sum));
        params.put("orderNumber", Integer.toString(orderId));
        params.put("paymentType", "AC");
        params.put("customerNumber", DataHolder.getInstance().getProfile().getID());
        PaymentParams paymentParams = new ShopParams(Integer.toString(SC_ID), params);
        Intent intent = ru.yandex.money.android.PaymentActivity.getBuilder(this)
                .setPaymentParams(paymentParams)
                .setClientId(CLIENT_ID)
                .build();
        startActivityForResult(intent, REQUEST_CODE);

Пускает на окно оплаты. Но после того как я ввел данные и нажал "Pay" приходит "AUTHORIZATION_REJECT".
В чем может быть проблема?

**Comment by yasevich** [comment]
Пока сложно сказать. Пробовали удалить данные приложения? Возможно instanceId больше не действителен.

**Comment by razer89** [comment]
Такая же проблема, удаление данных приложения не помогает

**Comment by mifkamaz** [comment]
В общем в один прекрасный момент все просто взяло и заработало.
Вроде связанно было с тем что бекендеры (чтоб их) не реализовали ответ на запрос от платежки нашему серверу.

**Comment by razer89** [comment]
у меня не работает по прежнему
