### ISSUE TITLE
ILLEGAL_PARAM_CLIENT_ID на https://demomoney.yandex.ru

### ISSUE THREAD

**Issue by razer89** [yandex-money/yandex-money-sdk-android#26]
Следующий код работает хорошо:

```
int userId = AccountManager.getInstance(this).getCurrentUser().getId();
HashMap<String, String> params = new HashMap<>();
params.put("shopId", SHOP_ID);
params.put("sum", "200");
params.put("customerNumber", String.valueOf(userId));
params.put("orderNumber", "YK-" + userId + "-" + System.currentTimeMillis());
params.put("paymentType", "AC");
Intent yandexIntent = ru.yandex.money.android.PaymentActivity.getBuilder(this)
     .setPaymentParams(new ShopParams(SC_ID, params))
     .setClientId(CLIENT_ID)
     .setHost("https://money.yandex.ru")
     .build();
startActivityForResult(yandexIntent, REQUEST_CODE);
```

Но когда пытаюсь повторить то же самое, только на `https://demomoney.yandex.ru`, в лог вылетает ошибка: `error=ILLEGAL_PARAM_CLIENT_ID,status=refused`
Код идентичный, за исключением `setHost()`

```
int userId = AccountManager.getInstance(this).getCurrentUser().getId();
HashMap<String, String> params = new HashMap<>();
params.put("shopId", SHOP_ID);
params.put("sum", "200");
params.put("customerNumber", String.valueOf(userId));
params.put("orderNumber", "YK-" + userId + "-" + System.currentTimeMillis());
params.put("paymentType", "AC");
Intent yandexIntent = ru.yandex.money.android.PaymentActivity.getBuilder(this)
     .setPaymentParams(new ShopParams(SC_ID, params))
     .setClientId(CLIENT_ID)
     .setHost("https://demomoney.yandex.ru")
     .build();
startActivityForResult(yandexIntent, REQUEST_CODE);
```

Я что-то делаю не так?

**Comment by yasevich** [comment]
Сергей, пока я проблем в Вашем коде не вижу. Но мне необходимо уточнить кое-что у коллег.

**Comment by yasevich** [comment]
Для demomoney нужно использовать другой CLIENT_ID, который отличен от боевого. Чтобы его получить, пройдите по [этой ссылке](https://demomoney.yandex.ru/myservices/new.xml).

**Comment by razer89** [comment]
Получил новый CLIENT_ID по вашей ссылке, но пришлось зарегистрировать новый аккаунт (не знаю, правильно ли это?), т.к. на существующий зарегистрировать не давало. С новым CLIENT_ID в лог теперь сыпется вот такое: `error=TECHNICAL_ERROR,status=refused`

**Comment by archiecrown** [comment]
@razer89  Так как решилась данная проблема?

**Comment by razer89** [comment]
@archiecrown пока не обновлялся до 3.3.0, еще не знаю
