### ISSUE TITLE
Реализация авторизации приложения для оплаты с Яндекс кошелька

### ISSUE THREAD

**Issue by AlexKravt** [yandex-money/yandex-money-sdk-android#28]
_yasevich_  **Добрый день.
Текущая версия SDK для Android позволяет совершать платежи только в неавторизованном состоянии с произвольной банковской карты. Но в SDK для Java есть все необходимые для этого методы. Пример того, как выполнить авторизацию описан здесь в секции Performing Request.
Старая версия SDK больше не поддерживается и гарантировать её правильную работу я не могу.**
*----------------------------------------------------*
Здравствуйте!
Выше Вы дали подсказку, на реализацию, но мне не совсем понятно как это использовать в webview? 
Так как судя по документации нужно реализовать перенаправление пользователя в браузер например (Chrome) и одновременно отправить запрос на подтверждение авторизации.
После чего нужно, каким то образом перехватить redirect.
В данной реализации, что Вы указали, используется, я так понял отправка данных методом POST через клиент client.createAuthorizationData(params) на URL авторизации и без открытия страницы пользователю.

Может я, что то не понимаю?
Спасибо!

**Comment by yasevich** [comment]
Сначала вам необходимо получить данные для авторизации в `WebView`. Например, вам необходим токен с правом `account-info`. Тогда код будет выглядеть примерно следующим образом:

```Java
ApiClient client = ... // ваш клиент

// необходимо задать параметры авторизации
AuthorizationParameters parameters = new AuthorizationParameters.Builder()
    .addScope(Scope.ACCOUNT_INFO)
    .setResponseType("code")
    .setRedirectUri(REDIRECT_URI)
    .build();

// клиент подготовит данные для авторизации
AuthorizationData data = client.createAuthorizationData(parameters);

WebView webView = ... // ваш WebView
webView.post(data.getUrl(), data.getParameters());
```

После того, как пользователь завершит процесс авторизации в `WebView`, `WebViewClient` будет перенаправлен на `REDIRECT_URI`. Перехватить его можно перегрузив метод `shouldOverrideUrlLoading(WebView view, String url)`:

```Java
@Override
public boolean shouldOverrideUrlLoading(WebView view, String url) {
    if (url.startsWith(REDIRECT_URI)) {
        requestAccessToken(url); // запросить постоянный access token вместо временного
    }
    return true;
}
```

Реализация метода `requestAccessToken` может отличаться в зависимости от требований вашего приложения, но может выглядеть примерно так:

```Java
void requestAccessToken(String redirectUri) {
    // разбираем параметры, полученные после редиректа
    AuthorizationCodeResponse response = AuthorizationCodeResponse.parse(redirectUri);

    if (response.error == null) {
        // пытаемся получить токен
        Token token = client.execute(new Token.Request(response.code, client.getClientId(), myRedirectUri, myClientSecret));
        if (token.error == null) {
            ... // если токен получен успешно, то неплохо бы его сохранить для повторного
            // использования, чтобы не заставлять пользователя авторизовываться вновь

            // устанавливаем полученный accessToken в ApiClient, чтобы выполнять запросы в
            // авторизованном состоянии
            client.setAccessToken(token.accessToken);
        } else {
            handleAuthorizationError(token.error);
        }
    } else {
        handleAuthorizationError(token.error);
    }
}
```

**Comment by AlexKravt** [comment]
Спасибо большое за подробный ответ, с примерным кодом, теперь мне всё понятно.
 Извините, что сам не догадался как реализовать. Так как не знал как передать параметры  для авторизации чрез WebView  по стандарту OAuth 2.0 
Теперь наконец сделаю авторизацию приложения.
И спасибо ещё раз!

**Comment by AlexKravt** [comment]
Здравствуйте!
Возник ещё один вопрос.
После авторизации в яндексе, не получаю редирект в виде своего адреса и параметров для получения временного токена и его замене.
Мои действия.
1) Отправляю запрос с параметрами авторизации приложения
2) Выводится на экран окно с формой авторизации
3) Ввожу данные для авторизации (логин пароль)
4) Получаю редирект в виде https://money.yandex.ru/oauth2/access?requestid=323935353034373636375f6533636534623137643866613733663232323037336561663737633135366xxxxxxxxxxxxxxxxxxx
 и выводиться окно с кнопкой (Продолжить)
5) Нажимаю на кнопку но ни чего не происходит, а лишь перезагружается окно в WebView с этим же URL.
По идее я должен получить редирект, но в метод shouldOverrideUrlLoading(WebView view, String url) ни чего не получаю, а вижу в методе **onPageFinished(WebView view, String url)** что страница просто перезагружается.

Может что не так делаю, подскажите пожалуйста.
Возможно в методе  shouldOverrideUrlLoading(WebView view, String url) при авторизации пользователя и получения окна браузера нужно опять передавать параметры авторизации?

Вот как выглядит этот метод у меня 
```
 @Override
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
            if(url.startsWith(REDIRECT_URI))
            {
                try {
                    requestAccessToken(url); // запросить постоянный access token вместо временного
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
               authView.loadUrl(url);  //<-- Передаём URL для получения формы авторизации пользователя

            return true;
        }
    }

```
