### ISSUE TITLE
Ошибка в параметре Scope

### ISSUE THREAD

**Issue by AlexKravt** [yandex-money/yandex-money-sdk-android#30]
Здравствуйте!
Заметил ошибку в параметре Scope при вызове метода **createPaymentScopeToAccount("ххххххх")** в параметр передаётся значение **paymentto-account("ххххххх")** вместо **payment.to-account("ххххххх")** поправьте пожалуйста", иначе приходиться использовать метод **setRawScope()**

**Comment by yasevich** [comment]
Вы можете добавить зависимость `compile 'com.yandex.money.api:yandex-money-sdk-java:6.1.0'` в проект. Новая версия содержит эти исправления.
