### ISSUE TITLE
in-app purchase, оплата цифровых товаров внутри приложения

### ISSUE THREAD

**Issue by spudi** [yandex-money/yandex-money-sdk-android#31]
Здравствуйте, мне нужно реализовать покупку цифровых товаров внутри приложения, я не могу найти примера как мне это сделать, нужно ли мне использовать P2P способ или оплату на yandex кошилек? в sample проекте я этого не нашел и не знаю с чего мне начать.

**Comment by yasevich** [comment]
Добрый день. Если вы хотите принимать платежи в приложении, возможно вам будет интересно воспользоваться решением, которое предлагает [Яндекс.Касса](https://kassa.yandex.ru/).

**Comment by spudi** [comment]
@yasevich могу ли я использовать следующий код для реализации платежей?
PaymentParams params = new P2pTransferParams.Builder("1234567812345678")
            .setAmount(new BigDecimal(1))
            .build();
    Intent intent = PaymentActivity.getBuilder(getBaseContext())
            .setPaymentParams(params)
            .setClientId(CLIENT_ID)
            .setHost(HOST)
            .build();
    startActivityForResult(intent, REQUEST_CODE);
и уточните пожайлуста что я должен использовать в качестве параметра номера ("1234567812345678"), это номер яндекс кошелька или номер какого-то счета в Яндекс.Кассе, как его получить?

**Comment by yasevich** [comment]
> и уточните пожайлуста что я должен использовать в качестве параметра номера ("1234567812345678"), это номер яндекс кошелька или номер какого-то счета в Яндекс.Кассе, как его получить?

Если вы в качестве параметров передаёте объект `P2pTransferParams`, то вы совершаете перевод на кошелёк Яндекс.Деньги. В конструктор `P2pTransferParams.Builder(String)` вам необходимо передать номер кошелька.

> аккаунт на Яндекс.Кассе настроен и все необходимые документы заполнены. Или вы посоветовали бы мне забить на ваше sdk и использовать способ с WebView?

Это зависит от требований к реализации. Если в приложении необходимо принимать платежи с банковских карт, то это SDK позволит вам избавить себя от необходимости реализации процесса оплаты.
