### ISSUE TITLE
Пример оплаты через банковские карты без авторизации

### ISSUE THREAD

**Issue by nikitoSha** [yandex-money/yandex-money-sdk-android#33]
Здравствуйте.
У Вас в примерах только оплата с яндекс.кошелька на кошелек и оплата мобильного телефона.
Где мне посмотреть пример оплаты с банковской карты без авторизации?
Все примеры, которые я видел - это примеры для интернет-магазинов с указанием shopId. У меня нет такого ИД, т.к. я - частное физическое лицо, а не ИП или юр. лицо.
Всё, что у меня есть, это идентификатор приложения из кабинета кошелька.

Помогите, пожалуйста, решить проблему с оплатой через банковские карты. Какие параметры мне надо указать? Куда внести ИД объекта из моей системы, чтобы было видно, что оплачивается именно он?

**Comment by nikitoSha** [comment]
Решил вопрос. P2P.

    public void showYandexPaymentActivity(String paySum){
        Intent intent = PaymentActivity.getBuilder(app_context)
                .setPaymentParams(new P2pTransferParams.Builder("4100......360")
                        .setAmount(new BigDecimal(paySum))
                        .create())
                .setClientId("1E4C16A750BBDA98C46.......5AAC4408516A077B319AD7DF")
                .setHost("https://money.yandex.ru")
                .build();
        startActivityForResult(intent, REQUEST_CODE_YANDEX_PAYMENT);
    }

**Comment by grabblesaur** [comment]
Так а как вы решили этот вопрос?

**Comment by nikitoSha** [comment]
@grabblesaur Сегодня, как освобожусь, напишу, Часа через 3,

**Comment by nikitoSha** [comment]
@grabblesaur держите!

>     public void showYandexPaymentActivity(String paySum){
        Intent intent = PaymentActivity.getBuilder(thisActivityContext)
                .setPaymentParams(new P2pTransferParams.Builder("410011052xxxxxx")
                        .setAmount(new BigDecimal(paySum))
                        .create())
                .setClientId("1E4C16A750BBDA98C460976356A.........C4408516A0..........9AD7DF")
                .setHost("https://money.yandex.ru")
                .build();
        startActivityForResult(intent, REQUEST_CODE_YANDEX_PAYMENT);
    }

**Comment by Carups** [comment]
@nikitoSha Я запускаю ваш пример, ввожу данные карточки потверждаю платёж, а на поседнем этапе всё ломается. Яндекс со словами "Ой, что-то произошло. Магазин отказывается принять платёж" предлагает повторить попытку перевода с тем же результатам. Не подскажете, что я делаю не так?

**Comment by nikitoSha** [comment]
@Carups Добрый день. К сожалению, я уже почти год не пользуюсь яндекс.деньгами и не в курсе их изменений. Работаю непосредственно с гугл. Возможно, что-то поменялось. Ради интереса я сегодня проверю этот момент и отпишусь здесь.

**Comment by nikitoSha** [comment]
Сегодня пришлось подключить снова яндекс.деньги. Подключил так же, как показывал пример выше, - всё работает. Карты можно сохранять, платежи проходят. Проверяйте ClientId и номер кошелька, куда делать перевод.
