### ISSUE TITLE
Сборка с ProGuard

### ISSUE THREAD

**Issue by Serg44** [yandex-money/yandex-money-sdk-android#34]
Модуль без проблем работает при тестовой сборке.

Исключение появляется в release сборке с proguard

`
Exception java.lang.InternalError:

rx.internal.util.unsafe.UnsafeAccess.isUnsafeAvailable (UnsafeAccess.java)
__null__.addressOf (UnsafeAccess.java)
rx.internal.util.unsafe.MpmcArrayQueueProducerField.<clinit> (MpmcArrayQueueProducerField.java)
rx.internal.util.ObjectPool.returnObject (ObjectPool.java)
__null__.start (ObjectPool.java)
__null__.initialize (ObjectPool.java)
rx.internal.util.ObjectPool.<init> (ObjectPool.java)
rx.internal.util.ObjectPool.<init> (ObjectPool.java)
rx.internal.util.RxRingBuffer$1.<init> (RxRingBuffer.java)
rx.internal.util.RxRingBuffer.<clinit> (RxRingBuffer.java)
rx.Observable.create (Observable.java)
__null__.lift (Observable.java)
__null__.fromCallable (Observable.java)
__null__.observeOn (Observable.java)
__null__.subscribe (Observable.java)
__null__.unsafeSubscribe (Observable.java)
__null__.subscribe (Observable.java)
ru.yandex.money.android.PaymentActivity.getBuilder (PaymentActivity.java)
__null__.getCards (PaymentActivity.java)
__null__.showWeb (PaymentActivity.java)
__null__.showError (PaymentActivity.java)
__null__.showSuccess (PaymentActivity.java)
__null__.performPaymentOperation (PaymentActivity.java)
__null__.performOperation (PaymentActivity.java)
__null__.onExternalPaymentReceived (PaymentActivity.java)
__null__.onExternalPaymentProcessed (PaymentActivity.java)
__null__.replaceFragment (PaymentActivity.java)
__null__.lambda$initPaymentProcess$4 (PaymentActivity.java)
__null__.lambda$performOperation$2 (PaymentActivity.java)
__null__.lambda$performOperation$1 (PaymentActivity.java)
__null__.lambda$performPaymentOperation$0 (PaymentActivity.java)
__null__.access$000 (PaymentActivity.java)
__null__.access$lambda$0 (PaymentActivity.java)
__null__.access$lambda$1 (PaymentActivity.java)
__null__.access$lambda$2 (PaymentActivity.java)
__null__.access$lambda$3 (PaymentActivity.java)
__null__.access$lambda$4 (PaymentActivity.java)
ru.yandex.money.android.PaymentActivity.initPaymentProcess (PaymentActivity.java)
ru.yandex.money.android.PaymentActivity.onCreate (PaymentActivity.java)
android.app.Activity.performCreate (Activity.java:6092)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1112)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2481)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2608)
android.app.ActivityThread.access$800 (ActivityThread.java:178)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1470)
android.os.Handler.dispatchMessage (Handler.java:111)
android.os.Looper.loop (Looper.java:194)
android.app.ActivityThread.main (ActivityThread.java:5637)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:959)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:754)
arrow_drop_down

Caused by java.lang.NoSuchFieldException: producerIndex

java.lang.Class.getDeclaredField (Class.java:890)
rx.internal.util.unsafe.UnsafeAccess.isUnsafeAvailable (UnsafeAccess.java)
__null__.addressOf (UnsafeAccess.java)
rx.internal.util.unsafe.MpmcArrayQueueProducerField.<clinit> (MpmcArrayQueueProducerField.java)
rx.internal.util.ObjectPool.returnObject (ObjectPool.java)
__null__.start (ObjectPool.java)
__null__.initialize (ObjectPool.java)
rx.internal.util.ObjectPool.<init> (ObjectPool.java)
rx.internal.util.ObjectPool.<init> (ObjectPool.java)
rx.internal.util.RxRingBuffer$1.<init> (RxRingBuffer.java)
rx.internal.util.RxRingBuffer.<clinit> (RxRingBuffer.java)
rx.Observable.create (Observable.java)
__null__.lift (Observable.java)
__null__.fromCallable (Observable.java)
__null__.observeOn (Observable.java)
__null__.subscribe (Observable.java)
__null__.unsafeSubscribe (Observable.java)
__null__.subscribe (Observable.java)
ru.yandex.money.android.PaymentActivity.getBuilder (PaymentActivity.java)
__null__.getCards (PaymentActivity.java)
__null__.showWeb (PaymentActivity.java)
__null__.showError (PaymentActivity.java)
__null__.showSuccess (PaymentActivity.java)
__null__.performPaymentOperation (PaymentActivity.java)
__null__.performOperation (PaymentActivity.java)
__null__.onExternalPaymentReceived (PaymentActivity.java)
__null__.onExternalPaymentProcessed (PaymentActivity.java)
__null__.replaceFragment (PaymentActivity.java)
__null__.lambda$initPaymentProcess$4 (PaymentActivity.java)
__null__.lambda$performOperation$2 (PaymentActivity.java)
__null__.lambda$performOperation$1 (PaymentActivity.java)
__null__.lambda$performPaymentOperation$0 (PaymentActivity.java)
__null__.access$000 (PaymentActivity.java)
__null__.access$lambda$0 (PaymentActivity.java)
__null__.access$lambda$1 (PaymentActivity.java)
__null__.access$lambda$2 (PaymentActivity.java)
__null__.access$lambda$3 (PaymentActivity.java)
__null__.access$lambda$4 (PaymentActivity.java)
ru.yandex.money.android.PaymentActivity.initPaymentProcess (PaymentActivity.java)
ru.yandex.money.android.PaymentActivity.onCreate (PaymentActivity.java)
android.app.Activity.performCreate (Activity.java:6092)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1112)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2481)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2608)
android.app.ActivityThread.access$800 (ActivityThread.java:178)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1470)
android.os.Handler.dispatchMessage (Handler.java:111)
android.os.Looper.loop (Looper.java:194)
android.app.ActivityThread.main (ActivityThread.java:5637)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:959)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:754)`

**Comment by yasevich** [comment]
Closed in favour of #39
