### ISSUE TITLE
Как указать способ оплаты "яндекс.деньги" ?

### ISSUE THREAD

**Issue by 1240** [yandex-money/yandex-money-sdk-android#35]
`HashMap<String, String> shopParams = new HashMap<>();
        shopParams.put("paymentType", "");
        shopParams.put("shopId", payment.getShopId());
        shopParams.put("scid", payment.getScid());
        shopParams.put("sum", payment.getSum().toString());
        shopParams.put("customerNumber", payment.getCustomerNumber());
        shopParams.put("orderNumber", payment.getOrderNumber().toString());
        PaymentParams paymentParams = new ShopParams(payment.getScid(), shopParams);
        Intent intent = PaymentActivity.getBuilder(this)
                .setPaymentParams(paymentParams)
                .setClientId(CLIENT_ID)
                .setHost(HOST)
                .build();
        startActivityForResult(intent, REQUEST_CODE);`
так же пробовал указывать PC в качестве paymentType
в дебаге внутри либы на моменте отображения сайта в WebView, в качестве урл в одном из парамтеров стабильно приходит "paymentType" -> "AC"

**Comment by yasevich** [comment]
Сейчас SDK не поддерживает оплату с помощью кошелька. Только с произвольной банковской карты.
