### ISSUE TITLE
Простейший пример интеграции java yandex-money-api без кассы

### ISSUE THREAD

**Issue by combatx007** [yandex-money/yandex-money-sdk-android#36]
Здравствуйте, я правильно понимаю, что для использования api и проведения платежей, касса не является обязательной? https://tech.yandex.ru/money/doc/dg/concepts/About-docpage/

В JAVA и разработке под android совершенно недавно. Всегда проще ориентироваться по примерам. Можете ли дать пример простейшего использования java api для проведения платежа?

**Comment by nikitoSha** [comment]
@combatx007 

	public void showYandexPaymentActivity(String paySum){
		Intent intent = PaymentActivity.getBuilder(thisActivityContext)
				.setPaymentParams(new P2pTransferParams.Builder("410...8560")
						.setAmount(new BigDecimal(paySum))
						.create())
				.setClientId("5CA3E495B4AEE52...792A039142D7B90C326D18F")
				.setHost("https://money.yandex.ru")
				.build();
		startActivityForResult(intent, REQUEST_CODE_YANDEX_PAYMENT);
	}
