### ISSUE TITLE
Тестовый режим работы с кассой.

### ISSUE THREAD

**Issue by w3ggy** [yandex-money/yandex-money-sdk-android#37]
Добрый день! Пытаюсь подключить Яндекс.Кассу в приложении: http://tech.yandex.ru/money/doc/dg/concepts/kassa-integration-docpage/ 
указана возможность перевода средств через Яндекс.Кассу, используя Android SDK. 
1. Заключил договор с Яндекс.Кассой.
2. Создал в Яндекс.Деньгах кошелек.
3. Создал приложение. После создания получил client_id
4. Прописал все данные в SDK Android
5. Формочка открывается, вроде как все работает (проверить пока нет возможности).
6. Для тестов хочу включить тестовый режим.
7. Создаю тестовый кошелек в http://demomoney.yandex.ru, создаю в нем приложение. Получаю новый client_id. 
8. Заменяю client_id и host в Android SDK (shopId и scId не меняю), при открытии формы вылетает ошибка: 
"E/ru.yandex.money.android.fragments.ErrorFragment: error=TECHNICAL_ERROR,status=refused"
9. Как включить тестовый режим?
Или что-то изначально неправильно? 
Для добавления платежей в мобильное приложение не требуется создание кошелька в Яндекс.Деньгах? Тогда откуда брать client_id? 
Или использование этого сдк невозможно при подключении к ЯК? В документации указана такая возможность, хотя в ТП мне сказали, что нет. Кому верить?

**Comment by lynnfield** [comment]
Здравствуйте. Возможно Вам больше подойдет другое решение Я.Кассы: https://github.com/yandex-money/yandex-checkout-android-sdk
