### ISSUE TITLE
Не проходит тестовый платеж

### ISSUE THREAD

**Issue by RomanByakov** [yandex-money/yandex-money-sdk-android#38]
HashMap<String, String> params = new HashMap<>();
        params.put("shopId", "98799");
        params.put("sum", "102.0");
        params.put("customerNumber", String.valueOf(42));
        params.put("orderNumber", "YK-" + 42 + "-" + System.currentTimeMillis());
        params.put("paymentType", "AC");

        Intent intent = PaymentActivity.getBuilder(this)
                .setPaymentParams(new ShopParams("548883", params))
                .setClientId(CLIENT_ID)
                .setHost(BuildConfig.YANDEX_HOST) // https://demomoney.yandex.ru
                .build();
        startActivityForResult(intent, REQUEST_CODE);

Response {"status":"refused","error":"technical_error"}

В поддержке посоветовали сменить ext_auth_success_uri, ext_auth_fail_uri выполняя данные запросы через сдк не понял как их сменить и целесообразно ли это вообще.

Заранее спасибо за помощь.

**Comment by lynnfield** [comment]
Здравствуйте. Возможно вы обращаетесь на тестовый хост, который не работает.
