### ISSUE TITLE
Возможность платить с банковской карты в этом приложении заблокирована

### ISSUE THREAD

**Issue by polygonator** [yandex-money/yandex-money-sdk-android#48]
Поскольку ответа на этот вопрос среди ранее заданных я не нашел, создаю новый. Все та же проблема, не могу совершить тестовый платеж после регистрации приложения. Прописал свой client_id.
error=TECHNICAL_ERROR,status=REFUSED

**Comment by lynnfield** [comment]
Здравствуйте. К сожалению мы больше не поддерживаем тестовых хост demomoney.yandex.ru.
Но мы добавим встроенный mock-сервер в рамках ПР #70.

**Comment by sergeGabrus** [comment]
Здравствуйте! Столкнулся с той же проблемой. Прописываю свой client_id, запускаю sample, однако после ввода карты и суммы получаю экран с сообщением "Возможность платить с банковской карты в этом приложении заблокирована". Подскажите пожалуйста, в чем же все-таки решение данной проблемы?
