### ISSUE TITLE
(PaymentActivity.java:503)? IllegalStateException Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by cosic** [yandex-money/yandex-money-sdk-android#49]
`
Fatal Exception: java.lang.IllegalStateExceptionCan not perform this action after onSaveInstanceState Raw Text
--
  | android.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:1438)
  | android.app.FragmentManagerImpl.popBackStack (FragmentManager.java:584)
  | ru.yandex.money.android.PaymentActivity.replaceFragment (PaymentActivity.java:503)
  | ru.yandex.money.android.PaymentActivity.showUnknownError (PaymentActivity.java:306)
  | ru.yandex.money.android.PaymentActivity.onOperationFailed (PaymentActivity.java:491)
  | ru.yandex.money.android.PaymentActivity$1.onPostExecute (PaymentActivity.java:404)
  | ru.yandex.money.android.PaymentActivity$1.onPostExecute (PaymentActivity.java:387)
  | android.os.AsyncTask.finish (AsyncTask.java:660)
`

для

`dependencies {
    compile 'com.yandex.money.api:yandex-money-sdk-android:4.1.0'
}`

**Comment by lynnfield** [comment]
Здравствуйте, поправили в рамках ПР #67
