### ISSUE TITLE
WebView не отображает платежную страницу

### ISSUE THREAD

**Issue by yargeel** [yandex-money/yandex-money-sdk-android#50]
Здравствуйте!

Я абсолютный новичок в YandexMoney и, насколько я понимаю, задаю вопрос не по адресу - но, возможно, вы сможете подсказать, куда с ним обратиться.
Бэкенд предоставляет для проведения оплаты url вида https://money.yandex.ru/api-pages/v2/payment-confirm/epl?orderId=XXX-000f-5000-a000-YYY - и этот url не отображается в WebView (белое поле). Загрузка страницы проходит "успешно" (без ошибок), в браузере и в версии приложения для iOS такой проблемы нет.
Буду признателен за совет - что делать.

**Comment by lynnfield** [comment]
Здравствуйте. Кажется по этому вопросу лучше обратиться в поддержку Яндекс Кассы.
https://kassa.yandex.ru/ask/
