### ISSUE TITLE
Есть ли возможность работы SDK на тестовых урл?

### ISSUE THREAD

**Issue by mitaichik** [yandex-money/yandex-money-sdk-android#6]
Добрый день. Пытаюсь сделать прием платежей. Зарегил аккаунт в кассе, теперь надо тестировать. Попытался сделать запрос, используя вот эти параметры:

```
/**
 * Параметры покупки
 */
public class Params implements com.yandex.money.api.methods.params.Params
{
	/**
	 * id заказа
	 */
	private int saleOrderId;

	/**
	 * сумма
	 */
	private int sum;

	public Params(OrderPreview preview)
	{
		saleOrderId = preview.saleOrderId;
		sum = preview.totalSum;
	}

	@Override
	public String getPatternId()
	{
		return "мой scid";
	}

	@Override
	public Map<String, String> makeParams()
	{
		Map<String, String> params = new HashMap<>();
		params.put("shopId", "мой shopId");
		params.put("scid", "мой scid");
		params.put("sum", "1.00");
		params.put("customerNumber", "123");
		params.put("paymentType", "AC");
		params.put("saleOrderId", Integer.toString(saleOrderId));
		return params;
	}
}

```
Вроде все необходимые параметры из протокола https://money.yandex.ru/doc.xml?id=526537 есть.

Получаю активити с надписью "Ой, платеж не прошел"

В логах - 05-28 14:11:16.310  18715-18715/ru.rzd E/ru.yandex.money.android.fragments.ErrorFragment﹕ error=TECHNICAL_ERROR,status=refused

Возникла идей, что это из-за зашитого url HostsProvider - может его надо сменить на тестовый как-то? Если да, то как и на какой?

И где узнать подробности ошибки, что я делаю не так?

**Comment by mitaichik** [comment]
C TECHNICAL_ERROR разобрался - она из-за того что юзается не тот URL для тестовго доступа (должен быть https:/demomoney.yandex.ru/api)

Теперь вопрос: можно ли его сменить для https://github.com/yandex-money/yandex-money-sdk-java/blob/master/src/main/java/com/yandex/money/api/net/HostsProvider.java без форконья? Вы предусмотрели такую возможность?

**Comment by raymank26** [comment]
Добрый день!

Вы можете передать параметр PaymentActivity.EXTRA_TEST_URL равный https://demomoney.yandex.ru (см. https://github.com/yandex-money/yandex-money-sdk-android/blob/master/library/src/main/java/ru/yandex/money/android/PaymentActivity.java#L371).

**Comment by mitaichik** [comment]
Спасибо.
